export default [
  {
    title: 'Tableau de bord',
    icon: { icon: 'tabler-layout-dashboard' },
    to: 'dashboard',
    action: 'read',
    subject: 'dashboard',
  },
  {
    title: 'Événements',
    icon: { icon: 'tabler-calendar-event' },
    to: 'events',
    action: 'read',
    subject: 'events',
  },
  {
    title: 'Événements en cours',
    icon: { icon: 'tabler-broadcast' },
    to: 'live-events',
    action: 'read',
    subject: 'events',
  },
  {
    title: 'Commandes',
    icon: { icon: 'tabler-shopping-cart' },
    to: 'orders',
    action: 'read',
    subject: 'bookings',
  },
  {
    title: 'Participants',
    icon: { icon: 'tabler-users' },
    to: 'participants',
    action: 'read',
    subject: 'users',
  },
  {
    title: 'Rapports & statistiques',
    icon: { icon: 'tabler-report-analytics' },
    to: 'reports',
    action: 'read',
    subject: 'dashboard',
  },
  {
    title: 'Paiements',
    icon: { icon: 'tabler-credit-card' },
    to: 'payments',
    action: 'read',
    subject: 'payments',
  },
  {
    title: 'Promotions',
    icon: { icon: 'tabler-rosette-discount' },
    to: 'promotions',
    action: 'read',
    subject: 'promotions',
  },
  {
    title: 'Billets vendus',
    icon: { icon: 'tabler-ticket' },
    to: 'tickets',
    action: 'read',
    subject: 'tickets',
  },
  {
    title: 'Coupons',
    icon: { icon: 'tabler-discount' },
    to: 'coupons',
    action: 'read',
    subject: 'coupons',
  },
  {
    title: 'Catalogue',
    icon: { icon: 'tabler-clipboard-list' },
    children: [
      {
        title: 'Catégories',
        icon: { icon: 'tabler-category' },
        to: 'categories',
        action: 'read',
        subject: 'categories',
      },
      {
        title: 'Lieux',
        icon: { icon: 'tabler-map-pin' },
        to: 'venues',
        action: 'read',
        subject: 'venues',
      },
      {
        title: 'Organisateurs',
        icon: { icon: 'tabler-building-store' },
        to: 'organizers',
        action: 'read',
        subject: 'organizers',
      },
    ],
  },
  {
    title: 'Administration',
    icon: { icon: 'tabler-settings' },
    children: [
      {
        title: 'Utilisateurs',
        icon: { icon: 'tabler-users' },
        to: 'users',
        action: 'read',
        subject: 'users',
      },
      {
        title: 'Rôles & permissions',
        icon: { icon: 'tabler-lock-cog' },
        to: 'roles',
        action: 'read',
        subject: 'administrators',
      },
      {
        title: 'Paramètres',
        icon: { icon: 'tabler-settings-cog' },
        to: 'settings',
        action: 'read',
        subject: 'administrators',
      },

      // Visible du seul organisateur : les heures d'ouverture du portique lui
      // appartiennent, et le serveur n'accorde `organizer-profile` qu'aux
      // comptes qui ont une fiche d'organisateur.
      {
        title: 'Contrôle d\'accès',
        icon: { icon: 'tabler-clock-check' },
        to: 'checkin-settings',
        action: 'read',
        subject: 'organizer-profile',
      },
      {
        title: 'Retraits',
        icon: { icon: 'tabler-cash' },
        to: 'withdrawals',
        action: 'read',
        subject: 'withdrawals',
      },
      {
        title: 'Notifications',
        icon: { icon: 'tabler-bell' },
        to: 'notifications',
        action: 'read',
        subject: 'notifications',
      },
    ],
  },
]
